language: c

compiler:
  - gcc

before_script:
  - ./install_deps.sh
  - export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH/usr/local/lib 

  
script: export CFLAGS="-I`pwd`/include $CFLAGS" &&  pwd && ls && make install && make tests
