language: c

compiler:
  - gcc

before_script:
  - ./install_deps.sh
  - export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH/usr/local/lib
  - export CFLAGS="-I`pwd`/include -L`pwd`/lib $CFLAGS"

  
script: pwd && ls && make install
